### ISSUE TITLE
[e2e debug] should serve multiport endpoints from pods

### ISSUE THREAD

**Issue by anusha94** [kubernetes-sigs/kpng#187]
What the test does -
Create a service with two ports but no Pods are added to the service yet.  The service MUST run and show empty set of endpoints. Add a Pod to the first port, service MUST list one endpoint for the Pod on that port. Add another Pod to the second port, service MUST list both the endpoints. Delete the first Pod and the service MUST list only the endpoint to the second Pod. Delete the second Pod and the service must now have empty set of endpoints.

**Comment by anusha94** [comment]
I'd like to debug this to learn more about services and endpoints!

/assign

**Comment by anusha94** [comment]
Sample failure - https://github.com/kubernetes-sigs/kpng/runs/4745155707?check_suite_focus=true

**Comment by qabpea** [comment]
This test is found at https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L823-L923
The endpoint is a simple abstraction of an object with an ip address and a port. In this test you will get two endpoints, one for each port..

I will look more into this and some other faults to come back with a better pinpointing of the problem

**Comment by anusha94** [comment]
Did some debugging - 

When the pod comes up, the corresponding entry for the service to route to the destination pod is missing in the iptables. pod logs have `iptables-restore failed` error - `Port '0' not valid`

It is caused by this line - https://github.com/kubernetes-sigs/kpng/blob/5c135f5b1f3b0c09dbd5851bb30d50be04d0be18/backends/iptables/iptables.go#L780

The `strconv.Itoa(svcInfo.TargetPort())` returns 0. This I think is because, in the service, targetport is a string.
```
spec:
  clusterIP: 10.96.74.56
  clusterIPs:
  - 10.96.74.56
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: portname1
    port: 80
    protocol: TCP
    targetPort: svc1
  - name: portname2
    port: 81
    protocol: TCP
    targetPort: svc2
  selector:
    testid: multi-endpoint-test-470b3990-2f14-4fdd-a22b-7a91e19d1f36
  sessionAffinity: None
  type: ClusterIP
```

In the k/k repo, found similar code that retrieves container port ip in case targetport is a string - https://github.com/kubernetes/kubernetes/blob/559091ba4f36a190e6876e0b164068385a7a992f/pkg/api/v1/pod/util.go#L30-L51

I believe something similar should be done in kpng. What do you think?
cc @nehaLohia27 @knabben
