### ISSUE TITLE
IPv6 does not work

### ISSUE THREAD

**Issue by uablrek** [kubernetes-sigs/kpng#32]
On a dual-stack K8s cluster with base family IPv4 services using IPv6 does not work, examples;
```
apiVersion: v1
kind: Service
metadata:
  name: mserver-ipv6
spec:
  ipFamilies:
    - IPv6
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-preferdual
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
```
Neither of these works. The `mserver-preferdual` have dual-stack addresses;
```
kubectl get svc mserver-preferdual -o json | jq .spec.clusterIPs
[
  "12.0.135.134",
  "fd00:4000::7133"
]
```
but not even the IPv4 address works.

On a dual-stack K8s cluster with base family IPv6 no services works.
