### ISSUE TITLE
An endpoint(slice)-controller

### ISSUE THREAD

**Issue by uablrek** [kubernetes-sigs/kpng#349]
I propose to implement an endpoint(slice)-controller in the same spirit as kpng, with an intelligent frontend and backend plugins.

/kind feature

### Rationale

When using [kpng](https://github.com/kubernetes-sigs/kpng) as a [specialized proxier](https://kubernetes.io/blog/2021/10/18/use-kpng-to-write-specialized-kube-proxiers/) with a `selector` in the service, K8s will populate endpoint-slices with POD addresses from the K8s   network (eth0). These addresses can most likely not be used by the specialized proxier (which may use another network). We would like to define our own endpoint-controller:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: special-service
  labels:
    service.kubernetes.io/service-proxy-name: my-kpng-based-proxy
    service.kubernetes.io/endpoint-controller-name: my-endpoint-controller
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
       { "name": "my-net" }
    ]'
spec:
  selector:
    app: my-app
  ports:
  - port: 6000
```

This has been proposed in https://github.com/kubernetes/kubernetes/issues/87412, presented and discussed on a sig/network meeting but has not been accepted. A specialized proxier will need a specialized endpoint-controller never the less.

An endpoint-controller must be able do dig up the POD addresses for a particular network. In the example I have used the same annotation as for PODs, but there may be better ways.

### K8s multi-network

Multi-network in K8s was presented on the [sig/network meeting Sept 15, 2022](https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit#bookmark=id.23z028aesgqp). A `Network` object was proposed and would be useful for a specialized endpoint-controller. *No KEP exists* so the multi-network proposal can't be discussed with normal K8s procedures. Multi-network in K8s will take years to realize even if accepted, so we can't wait for it. Most of an endpoint-controller written today will be re-usable in K8s with multi-network anyway.

### The selector problem

The proposal for a `endpoint-controller-name` was not really rejected but rather ignored. I think it would be fairly easy to implement (but I haven't tried), so IMHO this should be re-considered.

If the label is rejected it is possible to use a work-around:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: special-service
  labels:
    service.kubernetes.io/service-proxy-name: my-kpng-based-proxy
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
       { "name": "my-net" }
    ]'
    service.kubernetes.io/selector: app=my-app
spec:
  ports:
  - port: 6000
```

The `selector` is omitted and replaced with an annotation. This have a number of draw-backs, for instance headless services may be a problem.
