### ISSUE TITLE
Services with label service.kubernetes.io/service-proxy-name excluded

### ISSUE THREAD

**Issue by uablrek** [kubernetes-sigs/kpng#61]
To use a `kpng` based proxier for a special purpose while the regular kube-proxy is used for "normal" traffic you must use the `service.kubernetes.io/service-proxy-name` label, for example;
```yaml
apiVersion: v1
kind: Service
metadata:
  name: sctp-test
  labels:
    service.kubernetes.io/service-proxy-name: nordix-sctp
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mserver
  ports:
  - port: 6000
    name: sctpt
    protocol: SCTP
```
This will make the `kube-proxy` to ignore the service and a specialized proxier can subscribe for services with the desired "service-proxy-name" and handle only those.

But `kpng` is hardcoded to ignore all services having the service.kubernetes.io/service-proxy-name label;
https://github.com/kubernetes-sigs/kpng/blob/0c0a3c81012c365817287e915ccf0e1c90b5846d/jobs/kube2store/kube2store.go#L117-L122

There must be a configuration option for this.
